### PR TITLE
Adding more detailed security process and make /security work

### PR DESCRIPTION
**Pull request by evilpacket**
My thought is to get a security & from @lynnandtonic for the security page but left the beach in there as a placeholder. Please read and let me know what you think. From there we can modify the security.md's for the other projects to match this more detailed process.

The build works from the security.md file and the security.jade just includes that so it's only needed to be edited in the one place. magic.

Also note that the email addresses referenced might not be created yet until the internal ops request is finished.

### CODE REVIEW

**Comment by wraithgar** [comment]
include:md is pure magic +1 once we agree where in the header it should go.

**Comment by evilpacket** [comment]
It's common to be in the footer so I just put it there.

**Comment by wraithgar** [comment]
Yeah but for some reason it feels like github/twitter should go at the end.  There are enough links down there now that perhaps we should think about organizing.

**Comment by evilpacket** [comment]
Does something else need to be done on this before it can be merged?

**Comment by lynnandtonic** [comment]
@evilpacket I am working on the illustration today, but can add that in later.

Could you remove the `<p>` tags from inside the `<li>`s where it happens? Not a huge deal, and I can do that later on today too.

+1 from me.

**Comment by lynnandtonic** [comment]
I rearranged the links in the footer for now, but will create an issue to handle this better.

I left the markdown alone for the paragraphs/list items and adjusted the styling instead.

**Pull request merged**
