### PR TITLE
Content update

### PR DESCRIPTION
**Pull request by lynnandtonic**
- Adds logos to the home page, per #122
- Adds 'Amp' to the site navigation, per #123

### CODE REVIEW

**Comment by bear** [comment]
@lynnandtonic The commit "added team logos" seems to have content and html changes along with logos - is that on purpose?

**Comment by lynnandtonic** [comment]
@bear Yes, I also added the logos to the home page which required html and css updates. Sorry, I should be more specific!

**Comment by bear** [comment]
cool! then I'll merge this now - thanks!

**Comment by lynnandtonic** [comment]
Thanks @bear!

**Pull request merged**
