### PR TITLE
Add missing word?

### PR DESCRIPTION
**Pull request by khalillechelt**
I am not sure what is missing. My best guess is "simple".

### CODE REVIEW

**Comment by latentflip** [comment]
Shoot, I started merging some of these before remembering that docs/index.html is actually auto generated from the individual readme's of the relevant modules. I'll try and port the edits over but feel free to take stab at it if you like.

**Comment by khalillechelt** [comment]
OK I can transfer those  in a couple of days

**Comment by khalillechelt** [comment]
Can you maybe reopen the ones you closed already?

**Comment by latentflip** [comment]
Since they're pull requests it doesn't seem I can :(

**Comment by khalillechelt** [comment]
Ok i'll figure it out :)

**Comment by lynnandtonic** [comment]
Whoops, I should have looked at these comments before closing those other pull requests. @distilledhype Is there anything I can do to help you with these?

**Comment by khalillechelt** [comment]
@latentflip @lynnandtonic 

Okidoki friends I went through the closed PRs and sent new PRs on the respective READMEs. 

Closing this now. :heart:

**Comment by khalillechelt** [comment]
Oh and there is also a new PR for this issue on the respective README.

**Pull request closed without merging**
