### PR TITLE
update ubersicht link to display issues

### PR DESCRIPTION
**Pull request by tragiclifestories**
Currently the link gives you nothing but the filter controls.

### CODE REVIEW

**Comment by wraithgar** [comment]
Should this perhaps link to issues.ampersandjs.com instead?

**Comment by tragiclifestories** [comment]
Looks a lot more sensible, yes.

**Comment by tragiclifestories** [comment]
@wraithgar updated

**Comment by wraithgar** [comment]
Great, thanks for fixing this.

**Comment by tragiclifestories** [comment]
No worries. Finding something to fix was why I clicked the damn link in the first place ;-)

**Pull request merged**
